#
# /etc/sasl2/slapd.conf (0644): server slapd SASL configuration
#

#ldapdb_uri: ldapi://
#ldapdb_mech: EXTERNAL PLAIN LOGIN
#ldapdb_canon_attr: uid

# Mechlist: EXTERNAL DIGEST-MD5 CRAM-MD5 PLAIN LOGIN
mech_list: external plain login

# Use only slapd internal ldapdb plugin
auxprop_plugin: slapd

# Authenticate via saslauthd to allow hashed passwords: saslauthd, auxprop, pwcheck
pwcheck_method: auxprop

#olcRootDN: cn=admin,dc=ldap,dc=local
#olcRootPW: {SSHA}k1LTeSt0LmfzRQPtfPQ0EMzCBIKtF5o/eHTn5g==

# Path to saslauthd socket
saslauthd_path: /var/run/saslauthd/mux

#allow_plaintext: true
password-hash: {CLEARTEXT}
sasl-regexp: uid=(.*),cn=plain,cn=auth uid=$1,cn=users,dc=ldap,dc=local

# Enregistrer les logs LDAP
#log_level: trace conns config